### ISSUE TITLE
Self Explanatory

### ISSUE THREAD

**Issue by IonizedPro45** [LAION-AI/Open-Assistant#1152] opened 2023-02-05 06:15 UTC
![image](https://user-images.githubusercontent.com/64451674/216804748-572fa034-b298-4d75-b5a2-070f257c42a0.png)

**Comment by notmd** [comment] 2023-02-05 06:55
fixed by #1132

**Comment by AbdBarho** [comment] 2023-02-05 07:52
Duplicate of #1124, it is fixed, we just need to deploy the new version

**Closed by AbdBarho** 2023-02-05 07:52 UTC
