### ISSUE TITLE
Bug: Can't ask any questions anymore 

### ISSUE THREAD

**Issue by Danielpy24** [LAION-AI/Open-Assistant#3706] opened 2023-10-02 20:15 UTC
screen isn't available to ask questions like it's not even an option anymore. Nothing works

**Comment by krwb** [comment] 2023-10-04 03:01
Duplicate of https://github.com/LAION-AI/Open-Assistant/issues/3695.

But for your information, chat is down because it stopped being funded, running an ai for thousands if not millions of users is not cheep and open assistant relyed on a private investor to be able to afford to run the chat, the investor is no longer funding the project you can join the discord to stay up to date on the conversation. :)

**Comment by s0mt0chukwu** [comment] 2023-10-08 03:17
It's down

**Comment by s0mt0chukwu** [comment] 2023-10-08 03:18
> screen isn't available to ask questions like it's not even an option anymore. Nothing works

Restart device and clear browser cache

**Comment by andreaskoepf** [comment] 2023-11-28 07:35
https://youtu.be/gqtmUHhaplo?si=dwe6p0BxObXSNZyS

**Closed by andreaskoepf** 2023-11-28 07:35 UTC
