### ISSUE TITLE
Allow specialisation: Add tags to prompts so users can contribute in their areas of expertise.

### ISSUE THREAD

**Issue by distbit0** [LAION-AI/Open-Assistant#1242] opened 2023-02-06 12:25 UTC
Benefits: 
- Allows for non-programmers to not have to try to answer technical programming questions
- Allows for people to specialise in contributing to convos on things they are interested in/knowledgeable in
- Makes contributing more enjoyable, because people can chose to contribute to topics/tags they find most interesting
- Results in higher quality contributions, as more people knowledgeable about a topic will contribute to convos on said topic

Tags do not have to be perfect, so even 20 pre-selected ones would be a major improvement upon current situation. 

Examples of tags could be: 
- Maths
- Poetry
- Chat
- History
- Programming
- Grammar
- etc.

Source: Youtube commenter
![image](https://user-images.githubusercontent.com/10890247/216970784-1e14b807-b150-4a03-a79d-31d41d5ebc12.png)

**Comment by Sobsz** [comment] 2023-02-06 14:49
Something like this was already suggested at #1006. (Seems like a lot of people want it!)

**Comment by olliestanley** [comment] 2023-02-06 20:50
Yes, closing this as duplicate of #1006 but feel free to post your suggestions as a comment there :)

**Closed by olliestanley** 2023-02-06 20:50 UTC
