### ISSUE TITLE
Annoying automatic scrolling bug

### ISSUE THREAD

**Issue by Mathialist** [LAION-AI/Open-Assistant#845] opened 2023-01-19 11:25 UTC
On mobile, when I check an option in the report bug section of a message, the frame shift automatically by a bit.
![Screenshot_20230119_122115_Chrome](https://user-images.githubusercontent.com/20498406/213430380-d4106caf-926f-4e9c-b968-db3fc72c3148.jpg)

**Comment by AbdBarho** [comment] 2023-01-20 08:41
@Mathialist thank you, we have some other problems on mobile we need to also work on soon, #809

**Comment by notmd** [comment] 2023-01-21 13:52
I noticed this bug a few days ago too but I couldn't reproduce it now. Is it fixed?

**Comment by fozziethebeat** [comment] 2023-02-01 06:40
We've changed the flagging UI quite radically.  I'm going to close this as fixed given that its much more concise now.

**Closed by fozziethebeat** 2023-02-01 06:40 UTC
Labels: bug, website, beta feedback
