### ISSUE TITLE
Live chat skips words as it types until finished

### ISSUE THREAD

**Issue by mopishlynx23** [LAION-AI/Open-Assistant#2517] opened 2023-04-14 14:18 UTC
Not a huge issue, but when the AI is in the process of typing, it skips tokens as it goes and fixes it at the end. Was a bit difficult to catch on a screenshot but it makes using it annoying.

![image](https://user-images.githubusercontent.com/56328537/232069690-11776e69-deb8-4b18-b2bb-52f89e198088.png)

It's most noticeable when the code formatting glitches out because it skipped a grave.

**Comment by olliestanley** [comment] 2023-04-14 21:15
Duplicate of #2354. This issue is fixed in the codebase, just not deployed to prod yet. Hopefully we will get a new version out soon!

**Closed by olliestanley** 2023-04-14 21:15 UTC
