### ISSUE TITLE
The menu triggered when clicking on the message's ellipsis broke

### ISSUE THREAD

**Issue by CactiStaccingCrane** [LAION-AI/Open-Assistant#1732] opened 2023-02-19 04:03 UTC
When I'm doing tasks and click on the ellipsis (...), the menu is partially hidden and only show inside the message bubble frame. When you turn off the menu the whole message would also disappear.

**Comment by bitplane** [comment] 2023-02-19 06:09
Duplicate of #1698 - this is fixed in the latest version, but isn't deployed yet:

![image](https://user-images.githubusercontent.com/273059/219932043-681500d9-fe87-4559-a984-2e73dd94da7d.png)

**Closed by bitplane** 2023-02-19 06:09 UTC
