### ISSUE TITLE
`Improve User Experience by Adding Personalized Response Styles`

### ISSUE THREAD

**Issue by hemangjoshi37a** [LAION-AI/Open-Assistant#945] opened 2023-01-26 20:10 UTC
Hello @andreaskoepf, @rjmacarthy, @fozziethebeat, @othrayte, @AbdBarho, @notmd, @sanagno, @sbmaruf, @melvinebenezer, @dslvt, @ontocord, @pruksmhc, @Vechtomov, @Sobsz, @satani99 and @olliestanley,

I would like to propose a new feature for Open-Assistant to improve user experience by allowing users to set their preferred response style. This can be done by adding a new option in the user settings page where users can select from a list of predefined response styles.

This feature will not only enhance user engagement but also increase the perceived quality of the assistant. Additionally, it will also help in gathering data on user preferences, which can be used to further improve the assistant.

I would like to hear your thoughts and suggestions on this idea. Also, if anyone of you are interested in working on this feature, please let me know.

Best regards,
Hemang Joshi

**Comment by andreaskoepf** [comment] 2023-01-26 21:06
Can you give some examples of response styles that you have in mind?

**Comment by yk** [comment] 2023-01-26 22:07
please don't mass-ping people. we are all volunteers and busy enough. filing the issue in itself will already have someone looking at it

**Comment by Sobsz** [comment] 2023-01-26 22:35
Seconding yk's remark. Also, I've already somewhat brought this up at #871, though I admit that that proposal needs work.

**Comment by andreaskoepf** [comment] 2023-01-26 23:50
Duplicate of #871

**Closed by andreaskoepf** 2023-01-26 23:50 UTC
Labels: needs discussion
