### ISSUE TITLE
Mistitled labels when accessed from individual messages in https://open-assistant.io/ webapp

### ISSUE THREAD

**Issue by Tomodovodoo** [LAION-AI/Open-Assistant#1144] opened 2023-02-05 04:20 UTC
Hey, it seems the label titles are incorrect when accessing them from the options on messages in the webapp.

See attached screenshots
![image](https://user-images.githubusercontent.com/39548689/216801244-a70df306-6150-49ef-a236-e509ed56b4fb.png)
![image](https://user-images.githubusercontent.com/39548689/216801257-3cb0edf9-e362-42b5-a15b-71954bf2d734.png)

How it should look:
![image](https://user-images.githubusercontent.com/39548689/216801306-99a6ea04-0be3-4b2b-bc3d-c6a9cc45ca8a.png)

This always seems to happen when accessing the label tab from individual messages.

let me know if any more information is needed.

**Comment by AbdBarho** [comment] 2023-02-05 07:57
Duplicate of #1124, fixed in master, waiting for deployment.

**Closed by AbdBarho** 2023-02-05 07:57 UTC
