### ISSUE TITLE
Provide built in text formatting 

### ISSUE THREAD

**Issue by IonizedPro45** [LAION-AI/Open-Assistant#1147] opened 2023-02-05 04:36 UTC
I think that Open Assistants responses, especially when it comes to bullet points will be random and potentially inconsistent in a single prompt because there is no universal way to add formatting unlike many other text boxes such as Google Docs, Microsoft Word, the text box I'm typing in right now, etc. I think that it should generally be minimal, maybe just bullet points and hyperlinks.

**Comment by nikrtyd** [comment] 2023-02-05 06:32
I guess it's needed to Markdown-format Assistant responses, just like ChatGPT does it.

**Comment by AbdBarho** [comment] 2023-02-05 07:54
duplicate of #837, we can continue the discussion there.

**Closed by AbdBarho** 2023-02-05 07:54 UTC
Labels: website
