### ISSUE TITLE
Ability to stop generating?

### ISSUE THREAD

**Issue by gsaivinay** [LAION-AI/Open-Assistant#3193] opened 2023-05-18 09:17 UTC
Like the title says, is there any consideration to add `Stop Generating` button to open assistant chat interface? Might be useful if we want to quickly stop the model from generating, modify the prompt and send again.

**Comment by olliestanley** [comment] 2023-05-18 17:32
Duplicate of #2815

**Closed by olliestanley** 2023-05-18 17:32 UTC
