### ISSUE TITLE
Delete Chat Throwing Runtime Error & Text Running out of container

### ISSUE THREAD

**Issue by CertifiedJoon** [LAION-AI/Open-Assistant#3378] opened 2023-06-11 01:21 UTC
Error on delete
<img width="738" alt="image" src="https://github.com/LAION-AI/Open-Assistant/assets/61619422/e9a1892a-da3f-40c6-b296-b28dd6448a58">

Confirm delete popup text would run out of the box
<img width="620" alt="image" src="https://github.com/LAION-AI/Open-Assistant/assets/61619422/da042d48-5d73-414f-9828-855c66d8c205">

Delete process is quite problematic, there is also an issue assigned to me on #3306 

I would like to work on this issue and #3306 all together. Would that be fine?

**Comment by CertifiedJoon** [comment] 2023-06-11 04:27
Plus : The delete wouldn't trigger a toast popup, meanwhile, optOut does. So I am thinking, for consistency sake, we should add toast for successful delete.

**Comment by AbdBarho** [comment] 2023-06-11 20:12
I think this is a duplicate of https://github.com/LAION-AI/Open-Assistant/issues/3331?

**Comment by CertifiedJoon** [comment] 2023-06-12 06:27
@AbdBarho indeed. Should i close the relevant pr?

**Closed** 2023-06-13 05:38 UTC
Labels: website
