### ISSUE TITLE
chat deletion confirmation gets covered by chat response

### ISSUE THREAD

**Issue by wuhei** [LAION-AI/Open-Assistant#3267] opened 2023-05-31 06:27 UTC
![image](https://github.com/LAION-AI/Open-Assistant/assets/30749950/758948ab-0527-43e5-be62-0d942c52fdca)

**Comment by JaynouOliver** [comment] 2023-06-04 10:22
Can I work on it? Please assign it to me.

**Comment by olliestanley** [comment] 2023-06-06 08:18
> Can I work on it? Please assign it to me.

Feel free to take a look, I have assigned you

**Comment by davidak** [comment] 2023-06-06 08:32
I can reproduce this issue. The dialog appears behind the chat. Also, the chat UI does not get darker.

![Screenshot from 2023-06-06 10-30-58](https://github.com/LAION-AI/Open-Assistant/assets/91113/e04d23e7-3d57-443e-9c5a-8a7242e0d702)

**Comment by andreaskoepf** [comment] 2023-06-10 09:53
@JaynouOliver Were you able to set up a dev environment and reproduce the problem?

**Comment by CertifiedJoon** [comment] 2023-06-11 04:33
@andreaskoepf If @JaynouOliver is struggling to fix it, I think I can take over. I have been working on delete feature on #3378 and #3306.

**Comment by andreaskoepf** [comment] 2023-06-11 07:43
> I think I can take over.

Since we haven't heard back from @JaynouOliver I transfer the issue over to you. Thank you very much for helping to fix this!

**Closed** 2023-06-13 05:38 UTC
Labels: bug, website, UI/UX
