### ISSUE TITLE
Account corruption after switching to Google OAuth

### ISSUE THREAD

**Issue by DannyMac** [LAION-AI/Open-Assistant#3136] opened 2023-05-12 18:24 UTC
From the beginning, I've been using the Email option to sign in and noticed that Google OAuth had been added.  I successfully logged in using the Google OAuth, and had been doing some training tasks.  I then noticed today and see that my points had reset, but all my assistant chats that I created previously are present.  When I look at the leaderboard, I appear in it twice.  I appear to have "fractured" my account.  I then tried logging in via Email, hoping it would switch me back, but no change.

![image](https://github.com/LAION-AI/Open-Assistant/assets/3375673/b56da6da-0faf-4e9b-92d3-04cc4b0cba2f)

**Comment by AbdBarho** [comment] 2023-05-28 20:10
Hey, I tried around a lot and I could not reproduce this issue. Are you sure you used the same email for both logins?

What happens if you try to login with email?

**Comment by AbdBarho** [comment] 2023-06-01 19:46
Can you check what the user in https://github.com/LAION-AI/Open-Assistant/issues/3232 has reported? does it fix the situation for you?

Also, just for info, this is a big and complicated topic: https://github.com/LAION-AI/Open-Assistant/issues/3136

**Comment by andreaskoepf** [comment] 2023-06-09 18:21
I am closing this as it is indirectly tracked by https://github.com/LAION-AI/Open-Assistant/issues/3246

**Closed by andreaskoepf** 2023-06-09 18:21 UTC
Labels: bug, website
