### ISSUE TITLE
White error page after skipping or ranking assistant replies

### ISSUE THREAD

**Issue by Crusher50** [LAION-AI/Open-Assistant#1511] opened 2023-02-12 11:01 UTC
Whenever I skip a question or review the rankings of assistant responses when in the original order they were presented was correct, I get this white page with the following errors in the console log (I'm using Firefox if that could be the cause of this issue):

![image](https://user-images.githubusercontent.com/91010433/218306974-f854f1dc-6b52-4c72-9208-3069860cdddb.png)

![image](https://user-images.githubusercontent.com/91010433/218307007-820ddd79-2439-41ee-a697-74e5dc8b6805.png)

**Comment by noobyogi0010** [comment] 2023-02-13 17:20
@olliestanley I tried the same on Chrome but it works fine for me. Can you please add some steps to reproduce it?

**Comment by Crusher50** [comment] 2023-02-14 00:47
@noobyogi0010 Here's how I reproduce it on Firefox if that helps:

1. Open a task
- ![image](https://user-images.githubusercontent.com/91010433/218608933-93515685-d2f9-4d2c-b980-9921b1242eaa.png)
3. Press the skip task button
- ![image](https://user-images.githubusercontent.com/91010433/218608972-ec518445-a5fb-49d7-bdc1-7956fe656c4d.png)
5. white screen
- ![image](https://user-images.githubusercontent.com/91010433/218609006-857dcc60-a564-4efa-8a18-ffd2b0b2cc77.png)

**Comment by noobyogi0010** [comment] 2023-02-14 19:12
@Crusher50 Thanks for the detailed steps. Tried it on chrome but couldn't reproduce it. Will give it a try on Firefox.

**Comment by andreaskoepf** [comment] 2023-03-05 23:58
This should be fixed, pleas re-open if not.

**Closed by andreaskoepf** 2023-03-05 23:58 UTC
Labels: bug, website
