### ISSUE TITLE
No way to check personal score

### ISSUE THREAD

**Issue by VisenDev** [LAION-AI/Open-Assistant#1178] opened 2023-02-05 14:51 UTC
There is no way to see how much score you have earned unless you get onto the leaderboard. Only the top 20 people can see how many points they've earned.

Adding this would help improve gamification.

**Comment by swaptr** [comment] 2023-02-05 15:22
#1158 will fix this.

**Comment by jjmachan** [comment] 2023-02-05 16:31
+1 to this issue, would be really nice to have

**Comment by andreaskoepf** [comment] 2023-02-05 17:16
> Only the top 20 people can see how many points

We will display the personal score .. just one note: There is a next button on the top right on the leaderboards which allows you to page through the top 100 users.

**Comment by fozziethebeat** [comment] 2023-02-06 23:00
I'm going to close this as a duplicate of #747.  That issue aims to achieve the same goal

**Closed** 2023-02-07 05:50 UTC
