### ISSUE TITLE
Feature suggestion: User specialities/skills

### ISSUE THREAD

**Issue by migui06** [LAION-AI/Open-Assistant#1643] opened 2023-02-16 21:39 UTC
I feel like I came across a lot of questions that I didn't know anything about. I think that allowing the users to specify what he's good in, like math, physics, programming, language, history.
I think it would be a fun way to make sure that users don't waster their time answering blindly to questions or copy paste from ChatGPT and make the data set better.

We could have a list of all skillset that could be applied to chatGPT and either automatically detect what is the topic of a prompt, or ask users to label it.

I have no clue if its a good idea to add that, I would like to hear what anyone has to say about this.

**Comment by olliestanley** [comment] 2023-02-16 22:27
Closing as duplicate of #1006 #1315. In short - we would like to do this but it's not an easy feature and we already have a large chunk of data so it's relatively lower priority than some other tasks. If you'd be interested in working on it though, feel free to discuss on one of those other tickets!

**Closed by olliestanley** 2023-02-16 22:27 UTC
