### ISSUE TITLE
Tags on initial prompts

### ISSUE THREAD

**Issue by CheckMC** [LAION-AI/Open-Assistant#1810] opened 2023-02-23 02:58 UTC
I think a good way to get more assistant replies is to allow initial prompt creators to choose from tags. Could be as simple as Programming, Writing, AI, ect... 

This would allow those who are replying as Assistant to find things that are easier for them to reply to, or that they feel more confident replying to.

Thoughts?

**Comment by andreaskoepf** [comment] 2023-02-23 10:33
Closing this as it is a duplicate of https://github.com/LAION-AI/Open-Assistant/issues/1242 and https://github.com/LAION-AI/Open-Assistant/issues/1006 . Please continue discussion there. If someone is interested in working on this please go ahead.

**Closed by andreaskoepf** 2023-02-23 10:33 UTC

**Comment by andreaskoepf** [comment] 2023-02-23 11:07
Also related: https://github.com/LAION-AI/Open-Assistant/issues/1470
