### ISSUE TITLE
There should be a way to tweak the messages.

### ISSUE THREAD

**Issue by Syphikor** [LAION-AI/Open-Assistant#1925] opened 2023-03-02 02:23 UTC
![X89pFrbr79](https://user-images.githubusercontent.com/104782809/222298190-2a2cd00c-1d92-4afc-9041-37af3c6ff471.png)
### I am sure that i am not the only one who has experienced this but, i think the automated mind-numbing assistant replies (aka ChatGPT style) are exhausting for the mind.

It can be incredibly frustrating to read through all of their jargon-filled replies without being able to make any changes or even suggest them. The amount of nonsense that is spewed out on a regular basis when doing tasks is enough to exhaust anyone's mind and it becomes more and more irritating when you cannot do anything about it. What makes matters worse is that some of these replies contain almost no grammar whatsoever. 

This makes for an even worse experience as trying to decipher what they are saying becomes much harder than it needs to be. And if it exhausts me and other volunteers it will exhaust end users in the final product as well. In addition, the lack of feedback options other than the 'dislike' or 'report issue' buttons leaves us with very few ways in which volunteers can express their dissatisfaction or change anything wrong with the replies.

It would certainly help if there were more ways in which volunteers could interact with the prompter and the assistant replies and provide feedback or show change on how we could improve the services of the assistant chat messages as we encounter them, both from an assistant message content standpoint as well as from a grammatical perspective too.

Here is an idea:
![Hypha_pHzxvNq2](https://user-images.githubusercontent.com/104782809/222311123-6ca5dce5-bbfb-4b45-ab31-ac3d529d9faf.png)

Let's be honest, nobody wants to read through so much nonsense when it's not even creative or thought through especially when assistant replies could be simple and precise. 

Until then, however, i guess all volunteers who want to output quality and point out mistakes can do is grit their teeth and bear whatever nonsensical jargon responses come our way until some better feature which allows changing of the nonsense trees comes along.

**Comment by ArgiesDario** [comment] 2023-03-02 21:26
@Syphikor sounds like a great idea, but instead of having this second optional panel empty, where you have to complete all the changes that should be done, what do you think if we add in that panel the complete message you are reporting? This way you can just edit the words or parts directly to the original message, so when a moderator takes this report it could just replace the original message with yours

**Comment by Syphikor** [comment] 2023-03-03 02:05
Hi @ArgiesDario, 
I think that should do.

The example i gave was a brainstormed conceptual idea of what could be done. It can be even be a separate thing on its own. The idea wasn't fully developed, it was just a starting point, it could perhaps have similar functionality to a text diffchecker, just to be able to see what was changed and i think having a form of color-coding functionality could turn out to be useful because visible changes aid with sentence structure, phrasing, but also seeing what the volunteer changed.

I am sure it will aid the mods to go trough reports quickly and it should hypothetically speed up the process of going trough reports, so it can become something truly useful.

Any other ideas are welcomed in order to come up with the best possible solution.

**Comment by mashdragon** [comment] 2023-03-05 08:37
This has long been a suggested idea. I don't think there has been much traction. Someone has to create a task category dedicated to reviewing the edits.

See also #1005, #1126, #1542 (probably closest to what we want), #1718, #1729

My one suggestion if this gets implemented is that reviewers of edits should be able to see the changes in a colored diff view for ease of use in spotting what was changed.

**Comment by atemiz** [comment] 2023-03-05 09:01
It can be done in areas where everyone can reach the same result, such as spelling and logical errors. Of course, as long as the human factor is involved, it is still not possible to achieve absolute perfection. But, for example, an option can be presented, such as by which change a message that is considered rude can be made polite, and a message that is considered low quality can be made high quality. In this way, when the change suggested by the user is applied, the change in the labeling part can be updated for that user. Then multiple changes will need to be merged and conflicts will need to be ranked. Merging changes from multiple users may require re-evaluation at the very end.

There is a possibility that this process can create an endless cycle of updates and evaluations for messages. This results in human resources being spent on quality rather than quantity. It seems to me that at some point the message will become good enough and not worth further work on. However, how to achieve the optimum balance between quality and quantity will raise a new discussion topic.

**Comment by KosmosisDire** [comment] 2023-03-23 21:35
I think one problem with this idea is that people will rate the message based on it's contents. If those contents change then the ratings need to either be wiped and start over, or they will be likely be wrong. Especially the quality and helpfulness ratings.

**Comment by stephen-christie-ss** [comment] 2023-03-28 17:57
I have seen a lot of user replies that are something to the effect of "That's really hard to read, could you reformat it"? And many other times, I just see simple issues that I'd like to fix.

Having a diff with a note on what changed, or maybe written as a command on how to change it, might be a second useful dataset? Really though, I just want to be able to improve the baseline quality of the data when I see an obvious mistake.

Maybe instead of making a new task, the edited response and original can just be added to the Ranking task.

**Comment by olliestanley** [comment] 2023-06-12 17:46
Going to close this as a duplicate of #1542 but it is now actively being worked on

**Closed by olliestanley** 2023-06-12 17:46 UTC
Labels: website
