### ISSUE TITLE
"Not Appropriate" could be misunderstood

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#980] opened 2023-01-28 22:03 UTC
<img width="496" alt="image" src="https://user-images.githubusercontent.com/858040/215293046-704587ef-7b0a-45fe-8585-c544e0297e7b.png">

Users could interpret this as something like "none of the others", because they might confuse it with "not applicable"

**Comment by fozziethebeat** [comment] 2023-02-01 06:37
I'm going to close this as a duplicate of #1039.

My proposed fix for this and that issue is to have a tooltip for each label that better explains what they mean.

Also valid is figuring out better copy text for the buttons.

**Closed by fozziethebeat** 2023-02-01 06:37 UTC
Labels: website, UI/UX, needs discussion, beta feedback
