### ISSUE TITLE
Full Text popup during ranking does not handle newlines correctly

### ISSUE THREAD

**Issue by yk** [LAION-AI/Open-Assistant#1034] opened 2023-01-31 08:49 UTC
<img width="628" alt="image" src="https://user-images.githubusercontent.com/858040/215712403-66f09327-170c-4ef0-a56c-5ef886720e9f.png">

I wrote this so I know there are a couple of newlines in there. probably just needs some white-space: pre-line or so

**Comment by mashdragon** [comment] 2023-02-01 03:31
Duplicate of #1007

**Closed** 2023-02-01 05:46 UTC
Labels: website, good first issue, UI/UX
