### ISSUE TITLE
Delete button remains on screen after leaving element

### ISSUE THREAD

**Issue by AbdBarho** [LAION-AI/Open-Assistant#3072] opened 2023-05-07 10:18 UTC
Happens on `/chat` and in the subchats if the chat is not active

![image](https://user-images.githubusercontent.com/24505302/236671627-0849a719-963e-4e2a-b84b-001fc54efeec.png)

The code for this is here:
https://github.com/LAION-AI/Open-Assistant/blob/9ad4062ff8e254ad554f2017810039b06c5a5893/website/src/components/Chat/ChatListItem.tsx#L155-L172

**Comment by viju-sharma** [comment] 2023-05-08 08:37
Hey. Can you please assign it to me?

**Comment by Aditya-13** [comment] 2023-05-15 07:15
Hey @AbdBarho , i think the issue is fixed now.

As the code also changed :--

![Screenshot from 2023-05-15 12-44-08](https://github.com/LAION-AI/Open-Assistant/assets/91950158/7b15a9a9-63e7-43d6-a9bb-d074c85f52e8)


can you please check if the issue still persists?

**Comment by AbdBarho** [comment] 2023-05-15 08:46
No it is still a problem  :/

**Closed** 2023-05-26 08:39 UTC
Labels: bug, website, good first issue, UI/UX
