### ISSUE TITLE
Can't see how many users liked/disliked your replies now

### ISSUE THREAD

**Issue by aayojezuzchrezt** [LAION-AI/Open-Assistant#1372] opened 2023-02-08 21:41 UTC
Can't see how many users liked/disliked your replies after https://github.com/LAION-AI/Open-Assistant/pull/1302 update, I think it's important to know if users like or don't your answers

**Comment by mashdragon** [comment] 2023-02-08 21:41
Duplicate of #1367

**Closed** 2023-02-08 21:42 UTC
