### ISSUE TITLE
bug: Render new lines in "Rank Assistant Replies" / "Full Text"

### ISSUE THREAD

**Issue by lainisourgod** [LAION-AI/Open-Assistant#1027] opened 2023-01-30 21:46 UTC
I'm completing a "Rank Assistant Replies" task (1) and look at full text of one reply (2). It's surely missing some newlines → text is difficult to read.

![CleanShot 2023-01-31 at 01 42 19@2x](https://user-images.githubusercontent.com/24773652/215601882-962e13fd-c5fe-40c4-aad8-6d5184c0753b.png)

<img width="688" alt="image" src="https://user-images.githubusercontent.com/24773652/215601690-30b071d0-bbfe-43e4-810c-690b90e6141a.png">

I looked at computed html through dev tools (3), source text is indeed with new lines, they are just not rendered in UI.
<img width="396" alt="CleanShot 2023-01-31 at 01 40 59@2x" src="https://user-images.githubusercontent.com/24773652/215601666-7e06bd28-aba4-4cf1-89f0-dd8d0dbc0b7b.png">

**Comment by andreaskoepf** [comment] 2023-01-30 21:52
duplicate of https://github.com/LAION-AI/Open-Assistant/issues/1007

**Comment by fozziethebeat** [comment] 2023-02-01 06:32
Closing as it's a duplicate

**Closed by fozziethebeat** 2023-02-01 06:32 UTC
Labels: website, UI/UX, beta feedback
