### ISSUE TITLE
One I select an answer the button should turn green for submitting 

### ISSUE THREAD

**Issue by andrewm4894** [LAION-AI/Open-Assistant#810] opened 2023-01-17 21:21 UTC
It feels like selecting the answer when it's yes/no questions and also having to press Review and then submit feels like needless clicks.

Really though this is very minor and maybe not even worth trying to optimize the user flow too much just yet anyway.

**Comment by fozziethebeat** [comment] 2023-02-01 06:52
We've changed the spam review enough where I we've set a clear different color but also requested additional answers.  I'm closing this as working as intended

**Closed by fozziethebeat** 2023-02-01 06:52 UTC
Labels: good first issue, UI/UX, beta feedback
