### ISSUE TITLE
Reply doesn't show up unless I tap 'Back to chat list', and re-enter the conversation.

### ISSUE THREAD

**Issue by planetoryd** [LAION-AI/Open-Assistant#2406] opened 2023-04-08 17:03 UTC
when i sent a message

```haskell
Uncaught (in promise) ReferenceError: TextDecoderStream is not defined
    NextJS 15
[[id]-4e005c9ccdd15d60.js:1:5397](https://open-assistant.io/_next/static/chunks/pages/chat/%5Bid%5D-4e005c9ccdd15d60.js)
```

the entire convo loads with no problem, after re-entering.

all requests in the network tab are of 200 status code

**Comment by notmd** [comment] 2023-04-08 17:27
Hi can you share your browser name you are using and it's version?

**Comment by AbdBarho** [comment] 2023-04-08 17:44
update your firefox to version >=105

**Comment by planetoryd** [comment] 2023-04-08 18:55
I updated and the bug disappeared

**Comment by notmd** [comment] 2023-04-08 19:08
> btw, I tried to talk in Chinese. it spews complete nonsense

That might be the limitation of the current model. As the issue is resolved, I will close this, feel free to open new issue if you face any problem.

**Closed by notmd** 2023-04-08 19:08 UTC
Labels: bug, website, inference
