### ISSUE TITLE
Add hints for prompts (like in Bing)

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#3054] opened 2023-05-05 20:32 UTC
As title says.
![image](https://user-images.githubusercontent.com/122345469/236563299-ffeb160c-58c6-4906-97fa-100c89ea2fac.png)
![image](https://user-images.githubusercontent.com/122345469/236563316-02fa2285-43b5-4ff1-913a-5461b18edbb7.png)

**Comment by olliestanley** [comment] 2023-05-05 20:42
Isn't this a duplicate of #3010?

**Closed** 2023-05-05 20:54 UTC

**Comment by 0x22almostEvil** [comment] 2023-05-05 20:55
> Isn't this a duplicate of #3010?

Just was opening issues from undiscussed meeting themes, forgot to check if they're already exist ;P
