### ISSUE TITLE
Correct error message if offline

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [LAION-AI/Open-Assistant#1298] opened 2023-02-07 11:43 UTC
The system is currently responding: `Looks like no tasks were found.`
But you need to answer about network problems. For the user to check their internet connection.

**Comment by blankster** [comment] 2023-02-07 11:47
Duplicate of #1297

**Closed** 2023-02-10 23:45 UTC

**Comment by blankster** [comment] 2023-02-11 20:11
I can confirm, it never happened again :)
