### ISSUE TITLE
Action menu for messages is drawn within container

### ISSUE THREAD

**Issue by horribleCodes** [LAION-AI/Open-Assistant#1736] opened 2023-02-19 09:52 UTC
The menu for messages used to navigate to the message itself gets drawn within the container of the message itself. Since the container has a fixed width, the menu will be cut off and the text moved out of view.

![image](https://user-images.githubusercontent.com/7748313/219940820-af2e6ce4-bd89-42df-a59b-d4fd4d088838.png)

**Comment by horribleCodes** [comment] 2023-02-19 09:54
If it helps, here's the HTML of the menu element.

![image](https://user-images.githubusercontent.com/7748313/219941014-f7ebdc20-d677-49db-b812-9cd6f939a28a.png)

**Comment by jerzydziewierz** [comment] 2023-02-19 10:00
+1

**Comment by ElvinRath** [comment] 2023-02-19 10:02
Same issue here. There is 4 of us at the discord right now, and all 4 of us have it, so it seems general (?)

**Comment by bitplane** [comment] 2023-02-19 10:17
Duplicate of #1698

Fixed in `main` but not deployed yet :)

**Closed by bitplane** 2023-02-19 10:17 UTC
