### ISSUE TITLE
Cannot erase chats

### ISSUE THREAD

**Issue by almiares** [LAION-AI/Open-Assistant#2467] opened 2023-04-11 15:06 UTC
I want to erase the conversations with the assistant, clicking in the trash icon doesn't do anything. Inside the chat I don't have any option either.

![Screenshot_1](https://user-images.githubusercontent.com/45150536/231206018-b3e06aad-79b2-4dc2-a6bf-0cfb83a1b76c.png)

**Comment by olliestanley** [comment] 2023-04-11 15:22
Duplicate of #2384

**Closed** 2023-04-11 15:22 UTC

**Comment by almiares** [comment] 2023-04-14 03:04
what do you mean by not planned? why do you have the button then?

**Comment by olliestanley** [comment] 2023-04-14 06:55
> what do you mean by not planned? why do you have the button then? @olliestanley 

As I said in my message above, this issue is a duplicate of #2384, so there's no need for this one to remain open
