### ISSUE TITLE
Deleting Chat dialog has broken UI

### ISSUE THREAD

**Issue by davidak** [LAION-AI/Open-Assistant#3307] opened 2023-06-06 08:08 UTC
![Screenshot from 2023-06-06 10-03-59](https://github.com/LAION-AI/Open-Assistant/assets/91113/28ebeed7-88d6-4853-b7a8-f03cb70f8403)

The Text goes over the whole screen.

**Comment by olliestanley** [comment] 2023-06-06 08:18
Duplicate of #3267

**Closed by olliestanley** 2023-06-06 08:18 UTC

**Comment by davidak** [comment] 2023-06-06 08:34
Technically, it is a different issue, but i'm fine with closing this one if the solution fixes both.
