### ISSUE TITLE
Current use of volunteers in overall data collection strategy seems weird/inefficient?

### ISSUE THREAD

**Issue by josephrocca** [LAION-AI/Open-Assistant#1808] opened 2023-02-22 20:30 UTC
Please unceremoniously close this if I'm misunderstanding something or if this has been discussed elsewhere, but: There are millions of pieces of extremely high quality content online that have taken experts (with years of experience in their field) a lot of time to produce. Shouldn't those be added as assistant replies, and then people design user questions that match those pieces of content? It's really time-consuming to give a good answer to something, so it seems like a huge waste of person-hours to get them to manually research things that they're not experts in.

I understand that large datasets will be used, but I just don't see any need for people in the community painstakingly researching initial user questions/prompts to come up with their own answers that will almost always be lower quality than what is easily available online across various websites/publications.

Just to reiterate: Humans are obviously going to be needed for this data collection process. But it seems really inefficient to e.g. get a user to "write a 5 stanza rhyming poem about X" when you can instead collect a bunch of high-quality poems from the internet (on a broad array of topics) and then get the volunteers here to create user questions/commands that should lead to OpenAssistant producing that poem. That way it takes a few seconds instead of (up to) hours to produce a high-quality initial question-reply pair.

Again, apologies if I've misunderstood something, or if this has been discussed elsewhere.

**Comment by josephrocca** [comment] 2023-02-22 20:35
One way to easily "patch" this within the current paradigm might be to just allow people to provide both the initial question *and* the answer as a single task. That way if someone finds a great piece of content online, they can start a new task, paste it in as the assistant answer, and then just come up with a user prompt/question to match it.

**Comment by Ric71** [comment] 2023-02-22 21:19
I also imagine this was a great quality push. Obviously people had to check the licenses.

**Comment by CheckMC** [comment] 2023-02-22 22:42
I think part of the reason we aren't currently doing this is copyright.

**Comment by Ric71** [comment] 2023-02-22 22:57
@ CheckMC - But the copyright is an issue anyway. the answers can also be copied&pasted in the current approach.

**Comment by CheckMC** [comment] 2023-02-22 23:43
> @ CheckMC - But the copyright is an issue anyway. the answers can also be copied&pasted in the current approach. 

True. However, the guidelines and TOS say that content shouldn't violate copyright, at least I hope/think so.

**Comment by andreaskoepf** [comment] 2023-02-23 11:17
I am closing this since it is a duplicate of very older issues:

- [ Support for creating prompt-reply pair tasks #1030](https://github.com/LAION-AI/Open-Assistant/issues/1030)
- [ Allow to create a reply for task from Open in new tab view #1094 ](https://github.com/LAION-AI/Open-Assistant/issues/1094)

and related:
- [Feature suggestion: Given an assistant reply, let users write a prompt for it](https://github.com/LAION-AI/Open-Assistant/issues/1636])

Any help implementing the prompt-answer pair feature would be appreciated very much.

**Closed by andreaskoepf** 2023-02-23 11:17 UTC
