### ISSUE TITLE
Give me prompts matching my knowledge

### ISSUE THREAD

**Issue by tdkbzh** [LAION-AI/Open-Assistant#1269] opened 2023-02-06 20:18 UTC
I work in computer science.
I've been asked to answer prompts talking about biology - which i don't know anything about.

I'll want to work primarily on tasks involving my field of study.

Could it be possible to propose to the users tasks matching their knowledge / field of study / center of interests ?

**Comment by olliestanley** [comment] 2023-02-06 20:35
We want to add this but it will take time and we need someone to take on the task. We have issue #1006 to track this. If you want to help us add the feature comment on that issue and we can assign you :) Closing this as duplicate of the mentioned issue

**Closed by olliestanley** 2023-02-06 20:35 UTC
