### ISSUE TITLE
Doesn't have a requirements.txt

### ISSUE THREAD

**Issue by izam-mohammed** [LAION-AI/Open-Assistant#101] opened 2022-12-28 02:59 UTC
Can't find a requirements.txt file

**Comment by sryu1** [comment] 2022-12-28 04:25
I swear I saw one a few hours ago...

**Comment by sryu1** [comment] 2022-12-28 04:27
Maybe it was another repo hahaha...

**Comment by sryu1** [comment] 2022-12-28 05:00
Hey @izam-mohammed I realised there are requirements.txt files, in the subfolders of the repo.

**Comment by fozziethebeat** [comment] 2022-12-28 05:49
The backend code has one in `backend/` and the bot has one in `discord-bot/`

I'll be closing this as working as intended.

**Closed by fozziethebeat** 2022-12-28 05:49 UTC
