### ISSUE TITLE
Gmail Emails

### ISSUE THREAD

**Issue by TuxRobotics** [LAION-AI/Open-Assistant#2948] opened 2023-04-27 22:19 UTC
Your emails are being flagged by Gmail as "Dangerous" It dramatically delayed how long it took to show up in my inbox.

**Comment by olliestanley** [comment] 2023-04-29 10:16
Duplicate of a few other issues. We are aware, hopefully this will be fixed eventually

**Closed by olliestanley** 2023-04-29 10:16 UTC
