### ISSUE TITLE
Application error: a client-side exception has occurred (see the browser console for more information).

### ISSUE THREAD

**Issue by webplaytestxyz** [LAION-AI/Open-Assistant#1087] opened 2023-02-03 19:06 UTC
I have installed Docker Desktop and created new Dev Environment with this Github , so everything should be at default settings.

**Browser says there is this error when clicking any of the buttons on the screen:**
Application error: a client-side exception has occurred (see the browser console for more information).

**Browser console:**
```
Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/v1/auth/check. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 200.
2
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 13
[framework-3b5a00d5d7e8d93b.js:9:69816](http://localhost:3000/_next/static/chunks/framework-3b5a00d5d7e8d93b.js)
Error: Minified React error #130; visit https://reactjs.org/docs/error-decoder.html?invariant=130&args[]=undefined&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    NextJS 13
[main-a7a580e9c35c177d.js:1:10503](http://localhost:3000/_next/static/chunks/main-a7a580e9c35c177d.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-a7a580e9c35c177d.js:1:10520](http://localhost:3000/_next/static/chunks/main-a7a580e9c35c177d.js)
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error NetworkError when attempting to fetch resource. 
Object { error: {…}, url: "/api/auth/session", message: "NetworkError when attempting to fetch resource." }
[_app-ea7f0b508794703c.js:1:49703](http://localhost:3000/_next/static/chunks/pages/_app-ea7f0b508794703c.js)

​```

**Comment by fozziethebeat** [comment] 2023-02-06 12:24
Is this breaking anything? This is something I setup and haven't finished yet.  So it's semi-expected

**Comment by webplaytestxyz** [comment] 2023-02-06 23:17
I thought Open-Assistant would have had some functionality in it already. If you click a button and it gives that error, I think that means it is broken.

**Comment by fozziethebeat** [comment] 2023-02-07 07:50
By broken, I mean does this prevent you from using the application at all?  This is a http fetch call from the browser I know about but it shouldn't be interrupting the user experience.

**Comment by CactiStaccingCrane** [comment] 2023-02-08 01:33
It happens to me multiple times while adding replies in Vietnamese in open-assistant.io. Here's the console log:

`Error: React.Children.only expected to receive a single React element child.
    NextJS 16
        only
        E
        ak
        ui
        i
        oD
        oO
        oO
        oE
        oP
        r8
        oz
        eF
        ri
        nV
        nI`

`[framework-3b5a00d5d7e8d93b.js:9:69816](https://open-assistant.io/_next/static/chunks/framework-3b5a00d5d7e8d93b.js)
Error: React.Children.only expected to receive a single React element child.
    NextJS 16
        only
        E
        ak
        ui
        i
        oD
        oO
        oO
        oE
        oP
        r8
        oz
        eF
        ri
        nV
        nI`

`[main-a7a580e9c35c177d.js:1:10503](https://open-assistant.io/_next/static/chunks/main-a7a580e9c35c177d.js)
A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred [main-a7a580e9c35c177d.js:1:10520](https://open-assistant.io/_next/static/chunks/main-a7a580e9c35c177d.js)`

**Comment by fozziethebeat** [comment] 2023-02-08 05:05
These other errors look like different bugs.  I've verified that the `check` API call doesn't break anything.  These other issues seem like other bugs we'll have to hunt down.

**Comment by AbdBarho** [comment] 2023-03-05 08:12
I will close this one now, since the error is unclear and not reproducible, in case the issue persists, feel free to re-open.

**Closed by AbdBarho** 2023-03-05 08:12 UTC
Labels: website
