### ISSUE TITLE
JWT_SESSION_ERROR followed by Internal Server Error

### ISSUE THREAD

**Issue by RobertoDonPedro** [LAION-AI/Open-Assistant#2754] opened 2023-04-19 13:25 UTC
I get this error immediately after running `docker compose --profile ci --profile inference up --build --attach-dependencies` and clicking on url: http://localhost:3000
When I then click on "Chat" in the UI I get the error `Sorry, we encountered a server error. We're not sure what went wrong.` on the frontend and an `Internal Server Error` on the console.
I am running the latest release [v0.0.2-alpha13].

```
open-assistant-web-1                  | Datasource "db": PostgreSQL database "oasst_web", schema "public" at "webdb"
open-assistant-webdb-1                | 2023-04-19 13:07:56.065 UTC [75] LOG:  could not receive data from client: Connection reset by peer
open-assistant-web-1                  | 
open-assistant-web-1                  | The database is already in sync with the Prisma schema.
open-assistant-web-1                  | 
open-assistant-web-1                  | info  - Loaded env from /app/.env
open-assistant-web-1                  | Listening on port 3000 url: http://localhost:3000
open-assistant-web-1                  | [next-auth][error][JWT_SESSION_ERROR] 
open-assistant-web-1                  | https://next-auth.js.org/errors#jwt_session_error Cannot read properties of null (reading 'accounts') {
open-assistant-web-1                  |   message: "Cannot read properties of null (reading 'accounts')",
open-assistant-web-1                  |   stack: "TypeError: Cannot read properties of null (reading 'accounts')\n" +
open-assistant-web-1                  |     '    at convertToBackendUserCore (/app/.next/server/chunks/7225.js:392:14)\n' +
open-assistant-web-1                  |     '    at Object.jwt (/app/.next/server/pages/api/auth/[...nextauth].js:332:79)\n' +
open-assistant-web-1                  |     '    at async Object.session (/app/node_modules/next-auth/core/routes/session.js:53:21)\n' +
open-assistant-web-1                  |     '    at async AuthHandler (/app/node_modules/next-auth/core/index.js:158:27)\n' +
open-assistant-web-1                  |     '    at async NextAuthHandler (/app/node_modules/next-auth/next/index.js:24:19)\n' +
open-assistant-web-1                  |     '    at async Object.apiResolver (/app/node_modules/next/dist/server/api-utils/node.js:363:9)\n' +
open-assistant-web-1                  |     '    at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:474:9)\n' +
open-assistant-web-1                  |     '    at async Object.fn (/app/node_modules/next/dist/server/next-server.js:736:37)\n' +
open-assistant-web-1                  |     '    at async Router.execute (/app/node_modules/next/dist/server/router.js:252:36)\n' +
open-assistant-web-1                  |     '    at async NextNodeServer.run (/app/node_modules/next/dist/server/base-server.js:383:29)',
open-assistant-web-1                  |   name: 'TypeError'
open-assistant-web-1                  | }
```

**Comment by deftdawg** [comment] 2023-04-19 13:55
dupe of #2750?

**Closed** 2023-04-29 21:11 UTC
