### ISSUE TITLE
Periodically (daily/weekly) publish data under open licence 

### ISSUE THREAD

**Issue by 13hannes11** [LAION-AI/Open-Assistant#1162] opened 2023-02-05 09:55 UTC
För encouraging participation the data should be made available periodically. Maybe OpenStreetMap could be an inspiration for that.

**Comment by sheerun** [comment] 2023-02-05 11:08
Is it published at all? I could not find links to download

**Comment by olliestanley** [comment] 2023-02-05 11:16
The data will be released. Currently there is no process for periodically exporting it. If you want to work on a system for doing that feel free to look into the codebase. Some issues to consider include cleaning (incl. PII removal etc) the data before any release

**Comment by aidaho** [comment] 2023-02-05 11:54
As a bystander: it's the first question about the project that came to mind after watching Yannic Kilcher video on OpenAssistant.

**Comment by sheerun** [comment] 2023-02-05 12:10
Data should be released from day 0, not a pinky promise

**Comment by olliestanley** [comment] 2023-02-05 12:12
> Data should be released from day 0

As mentioned above, you can't just click a button and export the data as-is, because you risk releasing PII and/or illegal content and/or spam which hasn't been filtered out by the moderation process yet. We have not yet developed the system to process and export the data. If you want it to be a feature, make a PR adding that system instead of talking down other people's work please :)

**Comment by sheerun** [comment] 2023-02-05 12:15
I'll watch this thread then for updates :)

**Comment by Ibrahimabakar** [comment] 2023-02-05 12:31
اريد مساعده لانها لا استطيع اعمل بطريقه جيد

**Comment by jwstolk** [comment] 2023-02-05 12:32
(Also bystander) Mozilla Common Voice, which is in a similar situation, releases the data twice a year, which I think is a bit long of an interval. They also found out that it takes a lot of time to get everything formatted, checked and published for 100 languages. They also had an option for users to later changing their mind about having their data in the dataset, and their data was much larger since it contained also sound recordings.
I hope we can automate the publications a bit more and use a shorter interval.

**Comment by Ibrahimabakar** [comment] 2023-02-05 12:35
ريد بطريق جد التي يعملون في

**Comment by Ibrahimabakar** [comment] 2023-02-05 13:25
docker run -p 6070:80 dorowu/ubuntu-desktop-lxde-vnc

**Comment by Ibrahimabakar** [comment] 2023-02-05 13:25
docker run -p 6070:80 dorowu/ubuntu-desktop-lxde-vnc

**Comment by Ibrahimabakar** [comment] 2023-02-05 13:26
![image](https://user-images.githubusercontent.com/124394158/216821822-1894f677-5368-4b42-8a73-ab4e94fdfdd8.png)

**Comment by 13hannes11** [comment] 2023-02-05 14:56
Maybe one solution would be to release only data with sufficient user votes. Maybe some kind of export API could be provided for that.
Probably creating exports like this on the fly is not really feasible so we could generate such exports nightly weekly.

I haven't managed to look into the codebase itself but from my persepctive the following things need to be answered:

1. At which point is certain data considered to be safe to export
2. How should such an export dump look like? (SQL database dump containing only safe data, ZIP, etc?)
3. How should that data be made available? (e.g. API, automatic upload to some kind of hosting platform or something else)

The most important question and most difficult to answer question is 1.

**Comment by olliestanley** [comment] 2023-02-05 14:58
> Maybe one solution would be to release only data with sufficient user votes. Maybe some kind of export API could be provided for that. Probably creating exports like this on the fly is not really feasible so we could generate such exports nightly weekly.
> 
> I haven't managed to look into the codebase itself but from my persepctive the following things need to be answered:
> 
> 1. At which point is certain data considered to be safe to export
> 2. How should such an export dump look like? (SQL database dump containing only safe data, ZIP, etc?)
> 3. How should that data be made available? (e.g. API, automatic upload to some kind of hosting platform or something else)
> 
> The most important question and most difficult to answer question is 1.

So currently we have a message tree system where trees progress from states to initial submission to completion. Once a tree is in completed state it will no longer receive new rankings, ratings, labels etc as we have collected sufficient information. The starting point would therefore be to only consider trees which are completed. Then we would want to filter them by their quality etc according to the evaluation process, and ensure those tagged with PII/obscenity etc do not make it in

**Comment by andreaskoepf** [comment] 2023-02-06 21:38
> 



> Data should be released from day 0, not a pinky promise. Otherwise it's not Open Source. If someone wants to host forked version that releases all data immediately, only then I would consider contributing

Please go ahead and do this. You know where you find the source.

**Comment by mashdragon** [comment] 2023-03-05 08:49
@olliestanley Has there been any progress in creating a method for exporting and publishing the data? To date after reviewing thousands of messages I have not come across any instance of "PII" or "illegal" data. I hugely doubt there is much risk in that respect. A single publication of the current database in any format would boost everyone's confidence that our free labor is not going into a walled garden, even if it's not perfect (has spam, etc.)

Honestly the entire unfiltered set of message trees would be valuable for learning what types of messages the community doesn't think are appropriate.

If you need me to create a PR that exports the database for this to be possible... I think I could write code that does a rudimentary SQL dump.

**Comment by olliestanley** [comment] 2023-03-05 12:21
> @olliestanley Has there been any progress in creating a method for exporting and publishing the data? To date after reviewing thousands of messages I have not come across any instance of "PII" or "illegal" data. I hugely doubt there is much risk in that respect. A single publication of the current database in any format would boost everyone's confidence that our free labor is not going into a walled garden, even if it's not perfect (has spam, etc.)
> 
> Honestly the entire unfiltered set of message trees would be valuable for learning what types of messages the community doesn't think are appropriate.
> 
> If you need me to create a PR that exports the database for this to be possible... I think I could write code that does a rudimentary SQL dump.

In recent weeks an export script has been developed which can handle export of messages which are not flagged as spam, PII, etc. Features like exporting anonymised user/message IDs have also been added this week. This data is now starting to be used by a few people and some samples have been made public in the OA model eval repo. I think we are not far from being able to release more fully.

**Comment by Ibrahimabakar** [comment] 2023-03-05 12:27
Which data to write for you

‫في الأحد، 5 مارس 2023 في 1:22 م تمت كتابة ما يلي بواسطة ‪Oliver Stanley‬‏
***@***.***‬‏>:‬

**Comment by bitplane** [comment] 2023-03-21 03:25
Update: the plan is to release the initial model and dataset together on the 15th of April. So hang tight.

**Comment by olliestanley** [comment] 2023-04-10 09:35
Closing this issue as version 1 dataset release has been confirmed a while ago to be on the 15th, and nobody has shown interest in working on the automated process for regular releases,

**Closed by olliestanley** 2023-04-10 09:35 UTC
Labels: data

**Comment by nushoin** [comment] 2023-04-16 13:15
@olliestanley can you make an official commitment to periodically publish newly collected data - under a commercial-friendly open source license - in the future? Even once every six months would be fine.

Before contributing to a project such as this, I'd like to have a guarantee that my contributions would always be available and not locked behind some payment wall, unacceptable licensing or anything of the sort.

**Comment by olliestanley** [comment] 2023-04-16 13:18
> @olliestanley can you make an official commitment to periodically publish newly collected data - under a commercial-friendly open source license - in the future? Even once every six months would be fine.
> 
> Before contributing to a project such as this, I'd like to have a guarantee that my contributions would always be available and not locked behind some payment wall, unacceptable licensing or anything of the sort.

It's not my decision to make but we can definitely consider setting a regular cadence. Could you make a new issue suggesting this with your idea for a cadence/commitment? This thread got quite derailed so would be good to have a clean one
