### ISSUE TITLE
Give us more control on which questions we can answer to

### ISSUE THREAD

**Issue by stefangrotz** [LAION-AI/Open-Assistant#2761] opened 2023-04-19 15:47 UTC
Right now I basically have to answer to random questions, and I often skip through tenths of questions until I find one that I am capable to answer. Also it happens a lot that I research for an answer, open a lot of tabs for it and then I accidentally close the Open Assistant Tab and then I have to skip through many more questions until I find the original one again. Sometimes I don't find it again at all and all my research was for nothing.

What I want is two things:

1. A way to select the questions you want to answer, at best a search function through all open questions
2. A labeling system so filter out topics I am not interested in or select my field of expertise. 

I understand why you want to force us into this system of randomness, but this doesn't work when you have tons of very specific questions, that only experts can answer to.

**Comment by olliestanley** [comment] 2023-04-21 22:16
Yes, I think this is essentially a duplicate of #1006 and has been discussed since the early days.

The problem with this is just that it requires a lot of work and there is not much capacity to work on the data collection backend - the team is mostly working on the website, ML effort, and inference backend. If you would be interested to take a look at implementing a solution to this, we would be happy for you to do so, although it would of course need to be a reasonably lightweight solution.

**Closed** 2023-04-27 09:16 UTC
