### ISSUE TITLE
Having choice over "reply as assistant" topics

### ISSUE THREAD

**Issue by Thomasnerd06** [LAION-AI/Open-Assistant#1261] opened 2023-02-06 17:18 UTC
I think that to provide more accurate data people should be experts (to an extent) about what they're feeding in. For example, I have very little knowledge on fishing, but know a lot about 3d modelling. I think users should be able to choose what they respond to as an assistant. As I think this would lead to much more accurate data.

Maybe this may introduce bias into the dataset, though maybe a topic could be marked as an "opinion topic", and therefore not be able to be selected by anyone.

**Comment by chirag127** [comment] 2023-02-06 19:56
Ya, I'm also facing this issue that the questions that are being asked from are those on which I'm not expert or I don't know.

**Comment by olliestanley** [comment] 2023-02-06 20:36
We want to add this but it will take time and we need someone to take on the task. We have issue #1006 to track this. If you want to help us add the feature comment on that issue and we can assign you :) Closing this as duplicate of the mentioned issue

**Closed by olliestanley** 2023-02-06 20:36 UTC
