### ISSUE TITLE
Show points next to username / in user's profile

### ISSUE THREAD

**Issue by sedthh** [LAION-AI/Open-Assistant#1167] opened 2023-02-05 12:45 UTC
I think it would be useful to make the user's points visible outside of the leaderboard, to make them more motivated whenever they log in.

**Comment by olliestanley** [comment] 2023-02-05 14:38
Closing this as a duplicate of #747. It should be implemented by #1158 once outstanding issues are resolved.

**Closed by olliestanley** 2023-02-05 14:38 UTC
Labels: website, UI/UX, beta feedback
