### ISSUE TITLE
how delete account?

### ISSUE THREAD

**Issue by yremac** [LAION-AI/Open-Assistant#2041] opened 2023-03-11 09:02 UTC
how delete account?

**Comment by AbdBarho** [comment] 2023-03-11 11:08
I will close this as a duplicate of #1235 

We still don't have a solution in place. we are working on it.

The problem is not with deleting the account itself, but how we deal with the data. Should the data stay? or does it also get deleted?

We can continue the discussion in the other issue.

**Closed by AbdBarho** 2023-03-11 11:08 UTC
Labels: website, data
