### ISSUE TITLE
Cannot delete my account and chats

### ISSUE THREAD

**Issue by oniial** [LAION-AI/Open-Assistant#2488] opened 2023-04-12 19:38 UTC
The article 7.4 in the privacy policy states that we have the right to be forgotten and "demand that the controller erase personal data concerning you without undue delay". Yet, when I checked my settings for the deletion option it didn't appear.  Neither could I delete any previous chats that I sent through the app.

**Comment by olliestanley** [comment] 2023-04-12 19:41
Duplicate of #1235 #2384, these features will both be available soon

**Closed by olliestanley** 2023-04-12 19:41 UTC
