### ISSUE TITLE
Add ability to save custom (your own) presets and name it.

### ISSUE THREAD

**Issue by 0x22almostEvil** [LAION-AI/Open-Assistant#3055] opened 2023-05-05 20:41 UTC
As title says.

**Comment by olliestanley** [comment] 2023-05-05 20:44
I think this is also duplicate of #3035 :D

**Comment by 0x22almostEvil** [comment] 2023-05-05 20:54
> I think this is also duplicate of #3035 :D

Yep, sorry, haha

**Closed** 2023-05-05 20:54 UTC
